### PR TITLE
Release/1.1.0

### PR DESCRIPTION
**Pull request by tiller1010**
https://werkbotstudios.teamwork.com/#/tasks/29855709
https://werkbotstudios.teamwork.com/#/tasks/29722016

### Summary
- Fixed the insert and update methods in the searchable extensions
- Added the search modal feature

### Testing Steps
- [x] (optional) review these changes again
- [x] confirm the drafted release looks good https://github.com/werkbot/silverstripe-module-search/releases

### Issues/Concerns
- It looks like a merge commit is showing here. I'm pretty sure that is caused by an accidental "squash and merge" on a previous **release** PR. It should not cause any issues here though.
- It might be beneficial to create a `support/1.0.x` branch. That way we can add the "insert/update methods" patch under "1.0.5" without including the search modal feature. The search modal should not break compatibility, so this isn't necessary, just an option.
- I think we still have branch protection rules in place here. I can look into creating an automatically reviewed PR as we discussed, but we may need to disable them for this.

### Git Flow
- **DO NOT** delete "release/\*" or "hotfix/\*" branches after merging a PR. These are used to publish the next release, and they are deleted automatically.
- "Squash and merge" is good on "feature/\*" into "develop"
- "Create a merge commit" is good on "release/\*" or "hotfix/\*" into "master"

### CODE REVIEW

**Comment by tiller1010** [comment]
@aletail You can see a working example of an automatically approved PR here: https://github.com/tiller1010/silverstripe-module-search/pull/32

However, you cannot approve your own PRs using the auto-approve action (the bot can't review its own PR). In order for this to work, I had to add the repo secret "SOME_USERS_PAT", and set this to a personal access token of mine. You can see that my account acted as the reviewer.

**Comment by aletail** [comment]
> @aletail You can see a working example of an automatically approved PR here: [tiller1010#32](https://github.com/tiller1010/silverstripe-module-search/pull/32)
> 
> However, you cannot approve your own PRs using the auto-approve action (the bot can't review its own PR). In order for this to work, I had to add the repo secret "SOME_USERS_PAT", and set this to a personal access token of mine. You can see that my account acted as the reviewer.

That's cool, I am not sure I like the extra configuration - but there is no way around that I assume? I don't like the auto approve coming from a real user but its actually a bot doing it. Maybe I am overreacting but what are your thoughts on this process? Are we getting to convoluted/over complicating things?

**Comment by tiller1010** [comment]
@aletail
> That's cool, I am not sure I like the extra configuration - but there is no way around that I assume? I don't like the auto approve coming from a real user but its actually a bot doing it. Maybe I am overreacting but what are your thoughts on this process? Are we getting to convoluted/over complicating things?

Here is the error: https://github.com/tiller1010/silverstripe-module-search/actions/runs/3025113147/jobs/4867230533#step:10:15

I agree, this is a bit more than it should be. I'm of the opinion that GitHub is lacking a few settings in the branch protection rules that would make things easier. For now, I think most developers are forced into these types of workarounds.

**Comment by tiller1010** [comment]
@aletail It looks like we should create a "Machine User" for this https://docs.github.com/en/developers/overview/managing-deploy-keys#machine-users

**Comment by tiller1010** [comment]
@aletail It looks like the token did not work, https://github.com/werkbot/silverstripe-module-search/actions/runs/3099998089/jobs/5019788041#step:11:10

Some things to check
- Is the organization secret `SOME_USERS_PAT` set to a PAT of https://github.com/Werkbotdev ?
- Does the PAT have the proper scopes? repos and admin:org?

The PR **was** still created, and I simply approved it myself for now https://github.com/werkbot/silverstripe-module-search/pull/20

**Pull request merged**
