### PR TITLE
Ss module compliance

### PR DESCRIPTION
**Pull request by tiller1010**
https://werkbotstudios.teamwork.com/#/tasks/28273086

### Summary
SS module compliance.
- Added module files (CONTRIBUTING, CHANGELOG, etc...)
- Beautified php files
- Added search test

### Testing Steps
- [x] `dev/build`
- [ ] run test `vendor/bin/phpunit vendor/werkbot/werkbot-search/tests/SearchTest.php`
- [ ] confirm this works
- [ ] confirm module files look good

### CODE REVIEW

**Review by aletail — CHANGES_REQUESTED** [review]
This all looks great, but I could not get the test to pass. 
Here was the error:

```
LogicException: getItemPath returned null for SilverStripe\Dev\State\FixtureTestState. Try adding flush=1 to the test run.

C:\xampp-8.0\htdocs\silverstripe-install\vendor\silverstripe\framework\src\Dev\State\FixtureTestState.php:220
C:\xampp-8.0\htdocs\silverstripe-install\vendor\silverstripe\framework\src\Dev\State\FixtureTestState.php:195
C:\xampp-8.0\htdocs\silverstripe-install\vendor\silverstripe\framework\src\Dev\State\FixtureTestState.php:153
C:\xampp-8.0\htdocs\silverstripe-install\vendor\silverstripe\framework\src\Dev\State\FixtureTestState.php:152
C:\xampp-8.0\htdocs\silverstripe-install\vendor\silverstripe\framework\src\Dev\State\FixtureTestState.php:164
C:\xampp-8.0\htdocs\silverstripe-install\vendor\silverstripe\framework\src\Dev\State\FixtureTestState.php:66
C:\xampp-8.0\htdocs\silverstripe-install\vendor\silverstripe\framework\src\Dev\State\SapphireTestState.php:68
C:\xampp-8.0\htdocs\silverstripe-install\vendor\silverstripe\framework\src\Dev\SapphireTest.php:312
C:\xampp-8.0\htdocs\silverstripe-install\vendor\silverstripe\framework\src\Dev\FunctionalTest.php:107

ERRORS!
Tests: 1, Assertions: 0, Errors: 1.
```

I tried the flush 1 and deleting the cache folder, but same results :/ Yours is working right? I was on base install master, using php 8.0


Also, the badge poser does not pick up the license or php  - either see how we can fix or maybe we just remove those ones? Are they needed? Its the same for the seeder module

**Comment by tiller1010** [comment]
>I tried the flush 1 and deleting the cache folder, but same results :/ Yours is working right? I was on base install master, using php 8.0

I tested with php 7.4 and had no issues. I did have this same issue when running through php 8.0 though. This seems to be an issue with the `ClassManifest` `$classes` property. `werkbot\search\searchtest` is never an index:
```
public function getItemPath($name)
{
    $lowerName = strtolower($name);
    if($name == 'Werkbot\\Search\\SearchTest'){
        var_dump('source', $this->classes[$lowerName]);
        // Warning: Undefined array key "werkbot\search\searchtest" in /home/vagrant/ss-php-8/vendor/silverstripe/framework/src/Core/Manifest/ClassManifest.php on line 337
    }
```

Let me know if you have better luck with a 7.x php version. I can come back to this later.

>Also, the badge poser does not pick up the license or php - either see how we can fix or maybe we just remove those ones? Are they needed? Its the same for the seeder module

Perhaps the [composer file needs to be updated to include this](https://www.makeuseof.com/learn-how-to-distribute-your-php-packages-with-packagist/#create-composer-json-file). It is pulled from packagist, so a release may need to be made before these show.

**Comment by aletail** [comment]
> I tested with php 7.4 and had no issues. I did have this same issue when running through php 8.0 though. This seems to be an issue with the `ClassManifest` `$classes` property. `werkbot\search\searchtest` is never an index:
> 
> ```
> public function getItemPath($name)
> {
>     $lowerName = strtolower($name);
>     if($name == 'Werkbot\\Search\\SearchTest'){
>         var_dump('source', $this->classes[$lowerName]);
>         // Warning: Undefined array key "werkbot\search\searchtest" in /home/vagrant/ss-php-8/vendor/silverstripe/framework/src/Core/Manifest/ClassManifest.php on line 337
>     }
> ```
> 
> Let me know if you have better luck with a 7.x php version. I can come back to this later.

It must be unique to my setup then, I tested with 7.3 and 7.4 and get the same error...not sure why though. With the shopping cart tests, where I was having similar issues, clearing the cache folder worked well but that does not seem to be the case here.

> Perhaps the [composer file needs to be updated to include this](https://www.makeuseof.com/learn-how-to-distribute-your-php-packages-with-packagist/#create-composer-json-file). It is pulled from packagist, so a release may need to be made before these show.

Ahh yes probably

**Review by aletail — APPROVED** [review]
Everything looks good, marking approved

I will spend some time trying to determine the testing on my setup

**Pull request merged**
